<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="INNOWAVE-383" name="delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow" tests="10" failures="0" timestamp="14 set 2020 14:41:28 GMT" time="41.157" errors="1">
  <testcase name="step01" time="7.911" classname="delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow"/>
  <testcase name="step02" time="7.474" classname="delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow"/>
  <testcase name="step05" time="1.581" classname="delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow"/>
  <testcase name="step06" time="20.847" classname="delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow">
    <error type="java.lang.Exception" message="Test Failed on Step 6">
      <![CDATA[java.lang.Exception: Test Failed on Step 6
at delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow.step06(SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.Exception: Validation Failed on Step 6
at delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow.step06(SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow.java:191)
... 25 more
]]>
    </error>
  </testcase> <!-- step06 -->
  <testcase name="step07" time="0.000" classname="delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow">
    <skipped/>
  </testcase> <!-- step07 -->
  <testcase name="step10" time="0.000" classname="delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow">
    <skipped/>
  </testcase> <!-- step10 -->
  <testcase name="step09" time="0.000" classname="delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow">
    <skipped/>
  </testcase> <!-- step09 -->
  <testcase name="step08" time="0.000" classname="delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow">
    <skipped/>
  </testcase> <!-- step08 -->
  <testcase name="step03" time="2.159" classname="delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow"/>
  <testcase name="step04" time="1.185" classname="delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow"/>
</testsuite> <!-- delivery01.soi_150.SOI_150_TC4_PC_MobileOrderIntake_MACD_Flow -->
