<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="INNOWAVE-429" name="delivery02.soi_1312.SOI_1312_TC02_DS_ChineseWallsDuringQuoting_SalesSupportProfile" tests="5" failures="0" timestamp="24 Jul 2020 15:48:13 GMT" time="23.138" errors="1">
  <testcase name="step05" time="0.000" classname="delivery02.soi_1312.SOI_1312_TC02_DS_ChineseWallsDuringQuoting_SalesSupportProfile">
    <skipped/>
  </testcase> <!-- step05 -->
  <testcase name="step01" time="23.138" classname="delivery02.soi_1312.SOI_1312_TC02_DS_ChineseWallsDuringQuoting_SalesSupportProfile">
    <error type="java.lang.Exception" message="Test Failed on Step 1">
      <![CDATA[java.lang.Exception: Test Failed on Step 1
at delivery02.soi_1312.SOI_1312_TC02_DS_ChineseWallsDuringQuoting_SalesSupportProfile.step01(SOI_1312_TC02_DS_ChineseWallsDuringQuoting_SalesSupportProfile.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.Exception: Validation Failed on Step 1
at delivery02.soi_1312.SOI_1312_TC02_DS_ChineseWallsDuringQuoting_SalesSupportProfile.step01(SOI_1312_TC02_DS_ChineseWallsDuringQuoting_SalesSupportProfile.java:60)
... 25 more
]]>
    </error>
  </testcase> <!-- step01 -->
  <testcase name="step02" time="0.000" classname="delivery02.soi_1312.SOI_1312_TC02_DS_ChineseWallsDuringQuoting_SalesSupportProfile">
    <skipped/>
  </testcase> <!-- step02 -->
  <testcase name="step04" time="0.000" classname="delivery02.soi_1312.SOI_1312_TC02_DS_ChineseWallsDuringQuoting_SalesSupportProfile">
    <skipped/>
  </testcase> <!-- step04 -->
  <testcase name="step03" time="0.000" classname="delivery02.soi_1312.SOI_1312_TC02_DS_ChineseWallsDuringQuoting_SalesSupportProfile">
    <skipped/>
  </testcase> <!-- step03 -->
</testsuite> <!-- delivery02.soi_1312.SOI_1312_TC02_DS_ChineseWallsDuringQuoting_SalesSupportProfile -->
